// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: XTNewOrder.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "XTNewOrder.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace messages {

namespace {

const ::google::protobuf::Descriptor* XTNewOrder_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  XTNewOrder_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_XTNewOrder_2eproto() {
  protobuf_AddDesc_XTNewOrder_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "XTNewOrder.proto");
  GOOGLE_CHECK(file != NULL);
  XTNewOrder_descriptor_ = file->message_type(0);
  static const int XTNewOrder_offsets_[6] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(XTNewOrder, clordid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(XTNewOrder, symbol_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(XTNewOrder, side_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(XTNewOrder, ord_type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(XTNewOrder, quantity_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(XTNewOrder, price_),
  };
  XTNewOrder_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      XTNewOrder_descriptor_,
      XTNewOrder::default_instance_,
      XTNewOrder_offsets_,
      -1,
      -1,
      -1,
      sizeof(XTNewOrder),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(XTNewOrder, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(XTNewOrder, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_XTNewOrder_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      XTNewOrder_descriptor_, &XTNewOrder::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_XTNewOrder_2eproto() {
  delete XTNewOrder::default_instance_;
  delete XTNewOrder_reflection_;
}

void protobuf_AddDesc_XTNewOrder_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020XTNewOrder.proto\022\010messages\"n\n\nXTNewOrd"
    "er\022\017\n\007clordid\030\001 \001(\t\022\016\n\006symbol\030\002 \001(\t\022\014\n\004s"
    "ide\030\003 \001(\t\022\020\n\010ord_type\030\004 \001(\t\022\020\n\010quantity\030"
    "\005 \001(\r\022\r\n\005price\030\006 \001(\rb\006proto3", 148);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "XTNewOrder.proto", &protobuf_RegisterTypes);
  XTNewOrder::default_instance_ = new XTNewOrder();
  XTNewOrder::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_XTNewOrder_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_XTNewOrder_2eproto {
  StaticDescriptorInitializer_XTNewOrder_2eproto() {
    protobuf_AddDesc_XTNewOrder_2eproto();
  }
} static_descriptor_initializer_XTNewOrder_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#ifndef _MSC_VER
const int XTNewOrder::kClordidFieldNumber;
const int XTNewOrder::kSymbolFieldNumber;
const int XTNewOrder::kSideFieldNumber;
const int XTNewOrder::kOrdTypeFieldNumber;
const int XTNewOrder::kQuantityFieldNumber;
const int XTNewOrder::kPriceFieldNumber;
#endif  // !_MSC_VER

XTNewOrder::XTNewOrder()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:messages.XTNewOrder)
}

void XTNewOrder::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

XTNewOrder::XTNewOrder(const XTNewOrder& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:messages.XTNewOrder)
}

void XTNewOrder::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  clordid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  symbol_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  side_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ord_type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  quantity_ = 0u;
  price_ = 0u;
}

XTNewOrder::~XTNewOrder() {
  // @@protoc_insertion_point(destructor:messages.XTNewOrder)
  SharedDtor();
}

void XTNewOrder::SharedDtor() {
  clordid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  symbol_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  side_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ord_type_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void XTNewOrder::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* XTNewOrder::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return XTNewOrder_descriptor_;
}

const XTNewOrder& XTNewOrder::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_XTNewOrder_2eproto();
  return *default_instance_;
}

XTNewOrder* XTNewOrder::default_instance_ = NULL;

XTNewOrder* XTNewOrder::New(::google::protobuf::Arena* arena) const {
  XTNewOrder* n = new XTNewOrder;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void XTNewOrder::Clear() {
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<XTNewOrder*>(16)->f)

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(quantity_, price_);
  clordid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  symbol_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  side_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ord_type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());

#undef ZR_HELPER_
#undef ZR_

}

bool XTNewOrder::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:messages.XTNewOrder)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string clordid = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_clordid()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->clordid().data(), this->clordid().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "messages.XTNewOrder.clordid"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_symbol;
        break;
      }

      // optional string symbol = 2;
      case 2: {
        if (tag == 18) {
         parse_symbol:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_symbol()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->symbol().data(), this->symbol().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "messages.XTNewOrder.symbol"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_side;
        break;
      }

      // optional string side = 3;
      case 3: {
        if (tag == 26) {
         parse_side:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_side()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->side().data(), this->side().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "messages.XTNewOrder.side"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_ord_type;
        break;
      }

      // optional string ord_type = 4;
      case 4: {
        if (tag == 34) {
         parse_ord_type:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_ord_type()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->ord_type().data(), this->ord_type().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "messages.XTNewOrder.ord_type"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_quantity;
        break;
      }

      // optional uint32 quantity = 5;
      case 5: {
        if (tag == 40) {
         parse_quantity:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &quantity_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(48)) goto parse_price;
        break;
      }

      // optional uint32 price = 6;
      case 6: {
        if (tag == 48) {
         parse_price:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &price_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:messages.XTNewOrder)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:messages.XTNewOrder)
  return false;
#undef DO_
}

void XTNewOrder::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:messages.XTNewOrder)
  // optional string clordid = 1;
  if (this->clordid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->clordid().data(), this->clordid().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "messages.XTNewOrder.clordid");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->clordid(), output);
  }

  // optional string symbol = 2;
  if (this->symbol().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->symbol().data(), this->symbol().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "messages.XTNewOrder.symbol");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->symbol(), output);
  }

  // optional string side = 3;
  if (this->side().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->side().data(), this->side().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "messages.XTNewOrder.side");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->side(), output);
  }

  // optional string ord_type = 4;
  if (this->ord_type().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->ord_type().data(), this->ord_type().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "messages.XTNewOrder.ord_type");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->ord_type(), output);
  }

  // optional uint32 quantity = 5;
  if (this->quantity() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(5, this->quantity(), output);
  }

  // optional uint32 price = 6;
  if (this->price() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(6, this->price(), output);
  }

  // @@protoc_insertion_point(serialize_end:messages.XTNewOrder)
}

::google::protobuf::uint8* XTNewOrder::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:messages.XTNewOrder)
  // optional string clordid = 1;
  if (this->clordid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->clordid().data(), this->clordid().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "messages.XTNewOrder.clordid");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->clordid(), target);
  }

  // optional string symbol = 2;
  if (this->symbol().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->symbol().data(), this->symbol().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "messages.XTNewOrder.symbol");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->symbol(), target);
  }

  // optional string side = 3;
  if (this->side().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->side().data(), this->side().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "messages.XTNewOrder.side");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->side(), target);
  }

  // optional string ord_type = 4;
  if (this->ord_type().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->ord_type().data(), this->ord_type().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "messages.XTNewOrder.ord_type");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->ord_type(), target);
  }

  // optional uint32 quantity = 5;
  if (this->quantity() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(5, this->quantity(), target);
  }

  // optional uint32 price = 6;
  if (this->price() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(6, this->price(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:messages.XTNewOrder)
  return target;
}

int XTNewOrder::ByteSize() const {
  int total_size = 0;

  // optional string clordid = 1;
  if (this->clordid().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->clordid());
  }

  // optional string symbol = 2;
  if (this->symbol().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->symbol());
  }

  // optional string side = 3;
  if (this->side().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->side());
  }

  // optional string ord_type = 4;
  if (this->ord_type().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->ord_type());
  }

  // optional uint32 quantity = 5;
  if (this->quantity() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->quantity());
  }

  // optional uint32 price = 6;
  if (this->price() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->price());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void XTNewOrder::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const XTNewOrder* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const XTNewOrder>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void XTNewOrder::MergeFrom(const XTNewOrder& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.clordid().size() > 0) {

    clordid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.clordid_);
  }
  if (from.symbol().size() > 0) {

    symbol_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.symbol_);
  }
  if (from.side().size() > 0) {

    side_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.side_);
  }
  if (from.ord_type().size() > 0) {

    ord_type_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.ord_type_);
  }
  if (from.quantity() != 0) {
    set_quantity(from.quantity());
  }
  if (from.price() != 0) {
    set_price(from.price());
  }
}

void XTNewOrder::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void XTNewOrder::CopyFrom(const XTNewOrder& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool XTNewOrder::IsInitialized() const {

  return true;
}

void XTNewOrder::Swap(XTNewOrder* other) {
  if (other == this) return;
  InternalSwap(other);
}
void XTNewOrder::InternalSwap(XTNewOrder* other) {
  clordid_.Swap(&other->clordid_);
  symbol_.Swap(&other->symbol_);
  side_.Swap(&other->side_);
  ord_type_.Swap(&other->ord_type_);
  std::swap(quantity_, other->quantity_);
  std::swap(price_, other->price_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata XTNewOrder::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = XTNewOrder_descriptor_;
  metadata.reflection = XTNewOrder_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// XTNewOrder

// optional string clordid = 1;
void XTNewOrder::clear_clordid() {
  clordid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& XTNewOrder::clordid() const {
  // @@protoc_insertion_point(field_get:messages.XTNewOrder.clordid)
  return clordid_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void XTNewOrder::set_clordid(const ::std::string& value) {
  
  clordid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:messages.XTNewOrder.clordid)
}
 void XTNewOrder::set_clordid(const char* value) {
  
  clordid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:messages.XTNewOrder.clordid)
}
 void XTNewOrder::set_clordid(const char* value, size_t size) {
  
  clordid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:messages.XTNewOrder.clordid)
}
 ::std::string* XTNewOrder::mutable_clordid() {
  
  // @@protoc_insertion_point(field_mutable:messages.XTNewOrder.clordid)
  return clordid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* XTNewOrder::release_clordid() {
  
  return clordid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void XTNewOrder::set_allocated_clordid(::std::string* clordid) {
  if (clordid != NULL) {
    
  } else {
    
  }
  clordid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), clordid);
  // @@protoc_insertion_point(field_set_allocated:messages.XTNewOrder.clordid)
}

// optional string symbol = 2;
void XTNewOrder::clear_symbol() {
  symbol_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& XTNewOrder::symbol() const {
  // @@protoc_insertion_point(field_get:messages.XTNewOrder.symbol)
  return symbol_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void XTNewOrder::set_symbol(const ::std::string& value) {
  
  symbol_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:messages.XTNewOrder.symbol)
}
 void XTNewOrder::set_symbol(const char* value) {
  
  symbol_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:messages.XTNewOrder.symbol)
}
 void XTNewOrder::set_symbol(const char* value, size_t size) {
  
  symbol_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:messages.XTNewOrder.symbol)
}
 ::std::string* XTNewOrder::mutable_symbol() {
  
  // @@protoc_insertion_point(field_mutable:messages.XTNewOrder.symbol)
  return symbol_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* XTNewOrder::release_symbol() {
  
  return symbol_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void XTNewOrder::set_allocated_symbol(::std::string* symbol) {
  if (symbol != NULL) {
    
  } else {
    
  }
  symbol_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), symbol);
  // @@protoc_insertion_point(field_set_allocated:messages.XTNewOrder.symbol)
}

// optional string side = 3;
void XTNewOrder::clear_side() {
  side_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& XTNewOrder::side() const {
  // @@protoc_insertion_point(field_get:messages.XTNewOrder.side)
  return side_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void XTNewOrder::set_side(const ::std::string& value) {
  
  side_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:messages.XTNewOrder.side)
}
 void XTNewOrder::set_side(const char* value) {
  
  side_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:messages.XTNewOrder.side)
}
 void XTNewOrder::set_side(const char* value, size_t size) {
  
  side_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:messages.XTNewOrder.side)
}
 ::std::string* XTNewOrder::mutable_side() {
  
  // @@protoc_insertion_point(field_mutable:messages.XTNewOrder.side)
  return side_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* XTNewOrder::release_side() {
  
  return side_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void XTNewOrder::set_allocated_side(::std::string* side) {
  if (side != NULL) {
    
  } else {
    
  }
  side_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), side);
  // @@protoc_insertion_point(field_set_allocated:messages.XTNewOrder.side)
}

// optional string ord_type = 4;
void XTNewOrder::clear_ord_type() {
  ord_type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& XTNewOrder::ord_type() const {
  // @@protoc_insertion_point(field_get:messages.XTNewOrder.ord_type)
  return ord_type_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void XTNewOrder::set_ord_type(const ::std::string& value) {
  
  ord_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:messages.XTNewOrder.ord_type)
}
 void XTNewOrder::set_ord_type(const char* value) {
  
  ord_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:messages.XTNewOrder.ord_type)
}
 void XTNewOrder::set_ord_type(const char* value, size_t size) {
  
  ord_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:messages.XTNewOrder.ord_type)
}
 ::std::string* XTNewOrder::mutable_ord_type() {
  
  // @@protoc_insertion_point(field_mutable:messages.XTNewOrder.ord_type)
  return ord_type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* XTNewOrder::release_ord_type() {
  
  return ord_type_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void XTNewOrder::set_allocated_ord_type(::std::string* ord_type) {
  if (ord_type != NULL) {
    
  } else {
    
  }
  ord_type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ord_type);
  // @@protoc_insertion_point(field_set_allocated:messages.XTNewOrder.ord_type)
}

// optional uint32 quantity = 5;
void XTNewOrder::clear_quantity() {
  quantity_ = 0u;
}
 ::google::protobuf::uint32 XTNewOrder::quantity() const {
  // @@protoc_insertion_point(field_get:messages.XTNewOrder.quantity)
  return quantity_;
}
 void XTNewOrder::set_quantity(::google::protobuf::uint32 value) {
  
  quantity_ = value;
  // @@protoc_insertion_point(field_set:messages.XTNewOrder.quantity)
}

// optional uint32 price = 6;
void XTNewOrder::clear_price() {
  price_ = 0u;
}
 ::google::protobuf::uint32 XTNewOrder::price() const {
  // @@protoc_insertion_point(field_get:messages.XTNewOrder.price)
  return price_;
}
 void XTNewOrder::set_price(::google::protobuf::uint32 value) {
  
  price_ = value;
  // @@protoc_insertion_point(field_set:messages.XTNewOrder.price)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace messages

// @@protoc_insertion_point(global_scope)
