// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: XTExecution.proto

#ifndef PROTOBUF_XTExecution_2eproto__INCLUDED
#define PROTOBUF_XTExecution_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace messages {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_XTExecution_2eproto();
void protobuf_AssignDesc_XTExecution_2eproto();
void protobuf_ShutdownFile_XTExecution_2eproto();

class XTExecution;

// ===================================================================

class XTExecution : public ::google::protobuf::Message {
 public:
  XTExecution();
  virtual ~XTExecution();

  XTExecution(const XTExecution& from);

  inline XTExecution& operator=(const XTExecution& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const XTExecution& default_instance();

  void Swap(XTExecution* other);

  // implements Message ----------------------------------------------

  inline XTExecution* New() const { return New(NULL); }

  XTExecution* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const XTExecution& from);
  void MergeFrom(const XTExecution& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(XTExecution* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string clordid = 1;
  void clear_clordid();
  static const int kClordidFieldNumber = 1;
  const ::std::string& clordid() const;
  void set_clordid(const ::std::string& value);
  void set_clordid(const char* value);
  void set_clordid(const char* value, size_t size);
  ::std::string* mutable_clordid();
  ::std::string* release_clordid();
  void set_allocated_clordid(::std::string* clordid);

  // optional string symbol = 2;
  void clear_symbol();
  static const int kSymbolFieldNumber = 2;
  const ::std::string& symbol() const;
  void set_symbol(const ::std::string& value);
  void set_symbol(const char* value);
  void set_symbol(const char* value, size_t size);
  ::std::string* mutable_symbol();
  ::std::string* release_symbol();
  void set_allocated_symbol(::std::string* symbol);

  // optional string side = 3;
  void clear_side();
  static const int kSideFieldNumber = 3;
  const ::std::string& side() const;
  void set_side(const ::std::string& value);
  void set_side(const char* value);
  void set_side(const char* value, size_t size);
  ::std::string* mutable_side();
  ::std::string* release_side();
  void set_allocated_side(::std::string* side);

  // optional string ord_type = 4;
  void clear_ord_type();
  static const int kOrdTypeFieldNumber = 4;
  const ::std::string& ord_type() const;
  void set_ord_type(const ::std::string& value);
  void set_ord_type(const char* value);
  void set_ord_type(const char* value, size_t size);
  ::std::string* mutable_ord_type();
  ::std::string* release_ord_type();
  void set_allocated_ord_type(::std::string* ord_type);

  // optional uint32 quantity = 5;
  void clear_quantity();
  static const int kQuantityFieldNumber = 5;
  ::google::protobuf::uint32 quantity() const;
  void set_quantity(::google::protobuf::uint32 value);

  // optional uint32 price = 6;
  void clear_price();
  static const int kPriceFieldNumber = 6;
  ::google::protobuf::uint32 price() const;
  void set_price(::google::protobuf::uint32 value);

  // optional string ord_status = 7;
  void clear_ord_status();
  static const int kOrdStatusFieldNumber = 7;
  const ::std::string& ord_status() const;
  void set_ord_status(const ::std::string& value);
  void set_ord_status(const char* value);
  void set_ord_status(const char* value, size_t size);
  ::std::string* mutable_ord_status();
  ::std::string* release_ord_status();
  void set_allocated_ord_status(::std::string* ord_status);

  // optional string exec_type = 8;
  void clear_exec_type();
  static const int kExecTypeFieldNumber = 8;
  const ::std::string& exec_type() const;
  void set_exec_type(const ::std::string& value);
  void set_exec_type(const char* value);
  void set_exec_type(const char* value, size_t size);
  ::std::string* mutable_exec_type();
  ::std::string* release_exec_type();
  void set_allocated_exec_type(::std::string* exec_type);

  // optional uint32 last_qty = 9;
  void clear_last_qty();
  static const int kLastQtyFieldNumber = 9;
  ::google::protobuf::uint32 last_qty() const;
  void set_last_qty(::google::protobuf::uint32 value);

  // optional uint32 last_price = 10;
  void clear_last_price();
  static const int kLastPriceFieldNumber = 10;
  ::google::protobuf::uint32 last_price() const;
  void set_last_price(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:messages.XTExecution)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr clordid_;
  ::google::protobuf::internal::ArenaStringPtr symbol_;
  ::google::protobuf::internal::ArenaStringPtr side_;
  ::google::protobuf::internal::ArenaStringPtr ord_type_;
  ::google::protobuf::uint32 quantity_;
  ::google::protobuf::uint32 price_;
  ::google::protobuf::internal::ArenaStringPtr ord_status_;
  ::google::protobuf::internal::ArenaStringPtr exec_type_;
  ::google::protobuf::uint32 last_qty_;
  ::google::protobuf::uint32 last_price_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_XTExecution_2eproto();
  friend void protobuf_AssignDesc_XTExecution_2eproto();
  friend void protobuf_ShutdownFile_XTExecution_2eproto();

  void InitAsDefaultInstance();
  static XTExecution* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// XTExecution

// optional string clordid = 1;
inline void XTExecution::clear_clordid() {
  clordid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& XTExecution::clordid() const {
  // @@protoc_insertion_point(field_get:messages.XTExecution.clordid)
  return clordid_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void XTExecution::set_clordid(const ::std::string& value) {
  
  clordid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:messages.XTExecution.clordid)
}
inline void XTExecution::set_clordid(const char* value) {
  
  clordid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:messages.XTExecution.clordid)
}
inline void XTExecution::set_clordid(const char* value, size_t size) {
  
  clordid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:messages.XTExecution.clordid)
}
inline ::std::string* XTExecution::mutable_clordid() {
  
  // @@protoc_insertion_point(field_mutable:messages.XTExecution.clordid)
  return clordid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* XTExecution::release_clordid() {
  
  return clordid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void XTExecution::set_allocated_clordid(::std::string* clordid) {
  if (clordid != NULL) {
    
  } else {
    
  }
  clordid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), clordid);
  // @@protoc_insertion_point(field_set_allocated:messages.XTExecution.clordid)
}

// optional string symbol = 2;
inline void XTExecution::clear_symbol() {
  symbol_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& XTExecution::symbol() const {
  // @@protoc_insertion_point(field_get:messages.XTExecution.symbol)
  return symbol_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void XTExecution::set_symbol(const ::std::string& value) {
  
  symbol_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:messages.XTExecution.symbol)
}
inline void XTExecution::set_symbol(const char* value) {
  
  symbol_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:messages.XTExecution.symbol)
}
inline void XTExecution::set_symbol(const char* value, size_t size) {
  
  symbol_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:messages.XTExecution.symbol)
}
inline ::std::string* XTExecution::mutable_symbol() {
  
  // @@protoc_insertion_point(field_mutable:messages.XTExecution.symbol)
  return symbol_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* XTExecution::release_symbol() {
  
  return symbol_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void XTExecution::set_allocated_symbol(::std::string* symbol) {
  if (symbol != NULL) {
    
  } else {
    
  }
  symbol_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), symbol);
  // @@protoc_insertion_point(field_set_allocated:messages.XTExecution.symbol)
}

// optional string side = 3;
inline void XTExecution::clear_side() {
  side_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& XTExecution::side() const {
  // @@protoc_insertion_point(field_get:messages.XTExecution.side)
  return side_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void XTExecution::set_side(const ::std::string& value) {
  
  side_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:messages.XTExecution.side)
}
inline void XTExecution::set_side(const char* value) {
  
  side_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:messages.XTExecution.side)
}
inline void XTExecution::set_side(const char* value, size_t size) {
  
  side_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:messages.XTExecution.side)
}
inline ::std::string* XTExecution::mutable_side() {
  
  // @@protoc_insertion_point(field_mutable:messages.XTExecution.side)
  return side_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* XTExecution::release_side() {
  
  return side_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void XTExecution::set_allocated_side(::std::string* side) {
  if (side != NULL) {
    
  } else {
    
  }
  side_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), side);
  // @@protoc_insertion_point(field_set_allocated:messages.XTExecution.side)
}

// optional string ord_type = 4;
inline void XTExecution::clear_ord_type() {
  ord_type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& XTExecution::ord_type() const {
  // @@protoc_insertion_point(field_get:messages.XTExecution.ord_type)
  return ord_type_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void XTExecution::set_ord_type(const ::std::string& value) {
  
  ord_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:messages.XTExecution.ord_type)
}
inline void XTExecution::set_ord_type(const char* value) {
  
  ord_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:messages.XTExecution.ord_type)
}
inline void XTExecution::set_ord_type(const char* value, size_t size) {
  
  ord_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:messages.XTExecution.ord_type)
}
inline ::std::string* XTExecution::mutable_ord_type() {
  
  // @@protoc_insertion_point(field_mutable:messages.XTExecution.ord_type)
  return ord_type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* XTExecution::release_ord_type() {
  
  return ord_type_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void XTExecution::set_allocated_ord_type(::std::string* ord_type) {
  if (ord_type != NULL) {
    
  } else {
    
  }
  ord_type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ord_type);
  // @@protoc_insertion_point(field_set_allocated:messages.XTExecution.ord_type)
}

// optional uint32 quantity = 5;
inline void XTExecution::clear_quantity() {
  quantity_ = 0u;
}
inline ::google::protobuf::uint32 XTExecution::quantity() const {
  // @@protoc_insertion_point(field_get:messages.XTExecution.quantity)
  return quantity_;
}
inline void XTExecution::set_quantity(::google::protobuf::uint32 value) {
  
  quantity_ = value;
  // @@protoc_insertion_point(field_set:messages.XTExecution.quantity)
}

// optional uint32 price = 6;
inline void XTExecution::clear_price() {
  price_ = 0u;
}
inline ::google::protobuf::uint32 XTExecution::price() const {
  // @@protoc_insertion_point(field_get:messages.XTExecution.price)
  return price_;
}
inline void XTExecution::set_price(::google::protobuf::uint32 value) {
  
  price_ = value;
  // @@protoc_insertion_point(field_set:messages.XTExecution.price)
}

// optional string ord_status = 7;
inline void XTExecution::clear_ord_status() {
  ord_status_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& XTExecution::ord_status() const {
  // @@protoc_insertion_point(field_get:messages.XTExecution.ord_status)
  return ord_status_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void XTExecution::set_ord_status(const ::std::string& value) {
  
  ord_status_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:messages.XTExecution.ord_status)
}
inline void XTExecution::set_ord_status(const char* value) {
  
  ord_status_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:messages.XTExecution.ord_status)
}
inline void XTExecution::set_ord_status(const char* value, size_t size) {
  
  ord_status_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:messages.XTExecution.ord_status)
}
inline ::std::string* XTExecution::mutable_ord_status() {
  
  // @@protoc_insertion_point(field_mutable:messages.XTExecution.ord_status)
  return ord_status_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* XTExecution::release_ord_status() {
  
  return ord_status_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void XTExecution::set_allocated_ord_status(::std::string* ord_status) {
  if (ord_status != NULL) {
    
  } else {
    
  }
  ord_status_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ord_status);
  // @@protoc_insertion_point(field_set_allocated:messages.XTExecution.ord_status)
}

// optional string exec_type = 8;
inline void XTExecution::clear_exec_type() {
  exec_type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& XTExecution::exec_type() const {
  // @@protoc_insertion_point(field_get:messages.XTExecution.exec_type)
  return exec_type_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void XTExecution::set_exec_type(const ::std::string& value) {
  
  exec_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:messages.XTExecution.exec_type)
}
inline void XTExecution::set_exec_type(const char* value) {
  
  exec_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:messages.XTExecution.exec_type)
}
inline void XTExecution::set_exec_type(const char* value, size_t size) {
  
  exec_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:messages.XTExecution.exec_type)
}
inline ::std::string* XTExecution::mutable_exec_type() {
  
  // @@protoc_insertion_point(field_mutable:messages.XTExecution.exec_type)
  return exec_type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* XTExecution::release_exec_type() {
  
  return exec_type_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void XTExecution::set_allocated_exec_type(::std::string* exec_type) {
  if (exec_type != NULL) {
    
  } else {
    
  }
  exec_type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), exec_type);
  // @@protoc_insertion_point(field_set_allocated:messages.XTExecution.exec_type)
}

// optional uint32 last_qty = 9;
inline void XTExecution::clear_last_qty() {
  last_qty_ = 0u;
}
inline ::google::protobuf::uint32 XTExecution::last_qty() const {
  // @@protoc_insertion_point(field_get:messages.XTExecution.last_qty)
  return last_qty_;
}
inline void XTExecution::set_last_qty(::google::protobuf::uint32 value) {
  
  last_qty_ = value;
  // @@protoc_insertion_point(field_set:messages.XTExecution.last_qty)
}

// optional uint32 last_price = 10;
inline void XTExecution::clear_last_price() {
  last_price_ = 0u;
}
inline ::google::protobuf::uint32 XTExecution::last_price() const {
  // @@protoc_insertion_point(field_get:messages.XTExecution.last_price)
  return last_price_;
}
inline void XTExecution::set_last_price(::google::protobuf::uint32 value) {
  
  last_price_ = value;
  // @@protoc_insertion_point(field_set:messages.XTExecution.last_price)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace messages

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_XTExecution_2eproto__INCLUDED
