// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: XTNewOrder.proto

#ifndef PROTOBUF_XTNewOrder_2eproto__INCLUDED
#define PROTOBUF_XTNewOrder_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace messages {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_XTNewOrder_2eproto();
void protobuf_AssignDesc_XTNewOrder_2eproto();
void protobuf_ShutdownFile_XTNewOrder_2eproto();

class XTNewOrder;

// ===================================================================

class XTNewOrder : public ::google::protobuf::Message {
 public:
  XTNewOrder();
  virtual ~XTNewOrder();

  XTNewOrder(const XTNewOrder& from);

  inline XTNewOrder& operator=(const XTNewOrder& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const XTNewOrder& default_instance();

  void Swap(XTNewOrder* other);

  // implements Message ----------------------------------------------

  inline XTNewOrder* New() const { return New(NULL); }

  XTNewOrder* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const XTNewOrder& from);
  void MergeFrom(const XTNewOrder& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(XTNewOrder* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string clordid = 1;
  void clear_clordid();
  static const int kClordidFieldNumber = 1;
  const ::std::string& clordid() const;
  void set_clordid(const ::std::string& value);
  void set_clordid(const char* value);
  void set_clordid(const char* value, size_t size);
  ::std::string* mutable_clordid();
  ::std::string* release_clordid();
  void set_allocated_clordid(::std::string* clordid);

  // optional string symbol = 2;
  void clear_symbol();
  static const int kSymbolFieldNumber = 2;
  const ::std::string& symbol() const;
  void set_symbol(const ::std::string& value);
  void set_symbol(const char* value);
  void set_symbol(const char* value, size_t size);
  ::std::string* mutable_symbol();
  ::std::string* release_symbol();
  void set_allocated_symbol(::std::string* symbol);

  // optional string side = 3;
  void clear_side();
  static const int kSideFieldNumber = 3;
  const ::std::string& side() const;
  void set_side(const ::std::string& value);
  void set_side(const char* value);
  void set_side(const char* value, size_t size);
  ::std::string* mutable_side();
  ::std::string* release_side();
  void set_allocated_side(::std::string* side);

  // optional string ord_type = 4;
  void clear_ord_type();
  static const int kOrdTypeFieldNumber = 4;
  const ::std::string& ord_type() const;
  void set_ord_type(const ::std::string& value);
  void set_ord_type(const char* value);
  void set_ord_type(const char* value, size_t size);
  ::std::string* mutable_ord_type();
  ::std::string* release_ord_type();
  void set_allocated_ord_type(::std::string* ord_type);

  // optional uint32 quantity = 5;
  void clear_quantity();
  static const int kQuantityFieldNumber = 5;
  ::google::protobuf::uint32 quantity() const;
  void set_quantity(::google::protobuf::uint32 value);

  // optional uint32 price = 6;
  void clear_price();
  static const int kPriceFieldNumber = 6;
  ::google::protobuf::uint32 price() const;
  void set_price(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:messages.XTNewOrder)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr clordid_;
  ::google::protobuf::internal::ArenaStringPtr symbol_;
  ::google::protobuf::internal::ArenaStringPtr side_;
  ::google::protobuf::internal::ArenaStringPtr ord_type_;
  ::google::protobuf::uint32 quantity_;
  ::google::protobuf::uint32 price_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_XTNewOrder_2eproto();
  friend void protobuf_AssignDesc_XTNewOrder_2eproto();
  friend void protobuf_ShutdownFile_XTNewOrder_2eproto();

  void InitAsDefaultInstance();
  static XTNewOrder* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// XTNewOrder

// optional string clordid = 1;
inline void XTNewOrder::clear_clordid() {
  clordid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& XTNewOrder::clordid() const {
  // @@protoc_insertion_point(field_get:messages.XTNewOrder.clordid)
  return clordid_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void XTNewOrder::set_clordid(const ::std::string& value) {
  
  clordid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:messages.XTNewOrder.clordid)
}
inline void XTNewOrder::set_clordid(const char* value) {
  
  clordid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:messages.XTNewOrder.clordid)
}
inline void XTNewOrder::set_clordid(const char* value, size_t size) {
  
  clordid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:messages.XTNewOrder.clordid)
}
inline ::std::string* XTNewOrder::mutable_clordid() {
  
  // @@protoc_insertion_point(field_mutable:messages.XTNewOrder.clordid)
  return clordid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* XTNewOrder::release_clordid() {
  
  return clordid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void XTNewOrder::set_allocated_clordid(::std::string* clordid) {
  if (clordid != NULL) {
    
  } else {
    
  }
  clordid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), clordid);
  // @@protoc_insertion_point(field_set_allocated:messages.XTNewOrder.clordid)
}

// optional string symbol = 2;
inline void XTNewOrder::clear_symbol() {
  symbol_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& XTNewOrder::symbol() const {
  // @@protoc_insertion_point(field_get:messages.XTNewOrder.symbol)
  return symbol_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void XTNewOrder::set_symbol(const ::std::string& value) {
  
  symbol_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:messages.XTNewOrder.symbol)
}
inline void XTNewOrder::set_symbol(const char* value) {
  
  symbol_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:messages.XTNewOrder.symbol)
}
inline void XTNewOrder::set_symbol(const char* value, size_t size) {
  
  symbol_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:messages.XTNewOrder.symbol)
}
inline ::std::string* XTNewOrder::mutable_symbol() {
  
  // @@protoc_insertion_point(field_mutable:messages.XTNewOrder.symbol)
  return symbol_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* XTNewOrder::release_symbol() {
  
  return symbol_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void XTNewOrder::set_allocated_symbol(::std::string* symbol) {
  if (symbol != NULL) {
    
  } else {
    
  }
  symbol_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), symbol);
  // @@protoc_insertion_point(field_set_allocated:messages.XTNewOrder.symbol)
}

// optional string side = 3;
inline void XTNewOrder::clear_side() {
  side_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& XTNewOrder::side() const {
  // @@protoc_insertion_point(field_get:messages.XTNewOrder.side)
  return side_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void XTNewOrder::set_side(const ::std::string& value) {
  
  side_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:messages.XTNewOrder.side)
}
inline void XTNewOrder::set_side(const char* value) {
  
  side_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:messages.XTNewOrder.side)
}
inline void XTNewOrder::set_side(const char* value, size_t size) {
  
  side_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:messages.XTNewOrder.side)
}
inline ::std::string* XTNewOrder::mutable_side() {
  
  // @@protoc_insertion_point(field_mutable:messages.XTNewOrder.side)
  return side_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* XTNewOrder::release_side() {
  
  return side_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void XTNewOrder::set_allocated_side(::std::string* side) {
  if (side != NULL) {
    
  } else {
    
  }
  side_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), side);
  // @@protoc_insertion_point(field_set_allocated:messages.XTNewOrder.side)
}

// optional string ord_type = 4;
inline void XTNewOrder::clear_ord_type() {
  ord_type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& XTNewOrder::ord_type() const {
  // @@protoc_insertion_point(field_get:messages.XTNewOrder.ord_type)
  return ord_type_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void XTNewOrder::set_ord_type(const ::std::string& value) {
  
  ord_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:messages.XTNewOrder.ord_type)
}
inline void XTNewOrder::set_ord_type(const char* value) {
  
  ord_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:messages.XTNewOrder.ord_type)
}
inline void XTNewOrder::set_ord_type(const char* value, size_t size) {
  
  ord_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:messages.XTNewOrder.ord_type)
}
inline ::std::string* XTNewOrder::mutable_ord_type() {
  
  // @@protoc_insertion_point(field_mutable:messages.XTNewOrder.ord_type)
  return ord_type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* XTNewOrder::release_ord_type() {
  
  return ord_type_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void XTNewOrder::set_allocated_ord_type(::std::string* ord_type) {
  if (ord_type != NULL) {
    
  } else {
    
  }
  ord_type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ord_type);
  // @@protoc_insertion_point(field_set_allocated:messages.XTNewOrder.ord_type)
}

// optional uint32 quantity = 5;
inline void XTNewOrder::clear_quantity() {
  quantity_ = 0u;
}
inline ::google::protobuf::uint32 XTNewOrder::quantity() const {
  // @@protoc_insertion_point(field_get:messages.XTNewOrder.quantity)
  return quantity_;
}
inline void XTNewOrder::set_quantity(::google::protobuf::uint32 value) {
  
  quantity_ = value;
  // @@protoc_insertion_point(field_set:messages.XTNewOrder.quantity)
}

// optional uint32 price = 6;
inline void XTNewOrder::clear_price() {
  price_ = 0u;
}
inline ::google::protobuf::uint32 XTNewOrder::price() const {
  // @@protoc_insertion_point(field_get:messages.XTNewOrder.price)
  return price_;
}
inline void XTNewOrder::set_price(::google::protobuf::uint32 value) {
  
  price_ = value;
  // @@protoc_insertion_point(field_set:messages.XTNewOrder.price)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace messages

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_XTNewOrder_2eproto__INCLUDED
